// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    // THREATWEAVE Enterprise: We now use Clerk for authentication.
    // The browser automatically attaches the `__session` cookie to server function requests.
    // We no longer call `supabase.auth.getSession()` as it interferes with Clerk.
    return next({
      headers: {},
    });
  },
);
